// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSubscriberDO = "subscriber"

// SubscriberDO mapped from table <subscriber>
type SubscriberDO struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GmtCreate time.Time `gorm:"column:gmt_create;default:CURRENT_TIMESTAMP" json:"gmt_create"`
	GmtUpdate time.Time `gorm:"column:gmt_update;default:CURRENT_TIMESTAMP" json:"gmt_update"`
	Active    []uint8   `gorm:"column:active" json:"active"`
	Email     string    `gorm:"column:email;not null" json:"email"`
}

// TableName SubscriberDO's table name
func (*SubscriberDO) TableName() string {
	return TableNameSubscriberDO
}
