// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUsersDO = "users"

// UsersDO mapped from table <users>
type UsersDO struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GmtCreate time.Time `gorm:"column:gmt_create;default:CURRENT_TIMESTAMP" json:"gmt_create"`
	GmtUpdate time.Time `gorm:"column:gmt_update;default:CURRENT_TIMESTAMP" json:"gmt_update"`
	Username  string    `gorm:"column:username;not null" json:"username"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Avatar    string    `gorm:"column:avatar" json:"avatar"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Role      string    `gorm:"column:role;not null" json:"role"`
}

// TableName UsersDO's table name
func (*UsersDO) TableName() string {
	return TableNameUsersDO
}
