spring:
  application:
    name: birthday-reminder

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:}
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}

  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: ${MAIL_PORT:}
            class: javax.net.ssl.SSLSocketFactory

  threads:
    virtual:
      enabled: true


  quartz:
    job-store-type: jdbc

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false