spring:
  application:
    name: birthday-reminder

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  mail:
    host:
    port:
    username:
    password:

  quartz:
    job-store-type: jdbc


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false