# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # VuePress 需要完整提交历史来生成贡献者信息
        with:
          fetch-depth: 0
      - uses: imaegoo/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: qxdn/birthday-reminder
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd docs && yarn && yarn docs:build
          BUILD_DIR: .vitepress/dist
          